//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyMonoGame {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceFont {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFont() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyMonoGame.ResourceFont", typeof(ResourceFont).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XNBd}Microsoft.Xna.Framework.Content.SpriteFontReader, MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null/Microsoft.Xna.Framework.Content.Texture2DReader�Microsoft.Xna.Framework.Content.ListReader`1[[Microsoft.Xna.Framework.Rectangle, MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null]]/Microsoft.Xna.Framework.Content.RectangleReader�Microsoft.Xna.Framework.Content.ListReader`1[[System.Char, System.Private.CoreLib, Version=6.0.0.0, C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string A32 {
            get {
                return ResourceManager.GetString("A32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XNBd}Microsoft.Xna.Framework.Content.SpriteFontReader, MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null/Microsoft.Xna.Framework.Content.Texture2DReader�Microsoft.Xna.Framework.Content.ListReader`1[[Microsoft.Xna.Framework.Rectangle, MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null]]/Microsoft.Xna.Framework.Content.RectangleReader�Microsoft.Xna.Framework.Content.ListReader`1[[System.Char, System.Private.CoreLib, Version=6.0.0.0, C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string all {
            get {
                return ResourceManager.GetString("all", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XNBd}Microsoft.Xna.Framework.Content.SpriteFontReader, MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null/Microsoft.Xna.Framework.Content.Texture2DReader�Microsoft.Xna.Framework.Content.ListReader`1[[Microsoft.Xna.Framework.Rectangle, MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null]]/Microsoft.Xna.Framework.Content.RectangleReader�Microsoft.Xna.Framework.Content.ListReader`1[[System.Char, System.Private.CoreLib, Version=6.0.0.0, C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arial {
            get {
                return ResourceManager.GetString("Arial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XNBd}Microsoft.Xna.Framework.Content.SpriteFontReader, MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null/Microsoft.Xna.Framework.Content.Texture2DReader�Microsoft.Xna.Framework.Content.ListReader`1[[Microsoft.Xna.Framework.Rectangle, MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null]]/Microsoft.Xna.Framework.Content.RectangleReader�Microsoft.Xna.Framework.Content.ListReader`1[[System.Char, System.Private.CoreLib, Version=6.0.0.0, C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arial32 {
            get {
                return ResourceManager.GetString("Arial32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XNBd}Microsoft.Xna.Framework.Content.SpriteFontReader, MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null/Microsoft.Xna.Framework.Content.Texture2DReader�Microsoft.Xna.Framework.Content.ListReader`1[[Microsoft.Xna.Framework.Rectangle, MonoGame.Framework, Version=3.8.1.303, Culture=neutral, PublicKeyToken=null]]/Microsoft.Xna.Framework.Content.RectangleReader�Microsoft.Xna.Framework.Content.ListReader`1[[System.Char, System.Private.CoreLib, Version=6.0.0.0, C [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Arial48 {
            get {
                return ResourceManager.GetString("Arial48", resourceCulture);
            }
        }
    }
}
